name: Build Factory Image

on:
  workflow_dispatch:
  push:
    branches:
      - docker
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/build-push-action@v5.1.0
      with:
        dockerfile: Dockerfile
        build-args: PROJECT_NAME=factory,GIT_HASH=$GITHUB_SHA
        tags: ${{ secrets.DOCKER_IMAGE_NAME }}:$GITHUB_SHA
        

    # - name: Build Docker image
    #   run: |
    #     # docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:$GITHUB_SHA .
    #     bin/build $GITHUB_SHA

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_IMAGE_NAME }}:$GITHUB_SHA
